// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB988Xbb9iwsGElC6refQARmN560NmWYOA',
    appId: '1:545047816852:web:6a2e326d399a0c0e66e281',
    messagingSenderId: '545047816852',
    projectId: 'shikakugame-ddfcf',
    authDomain: 'shikakugame-ddfcf.firebaseapp.com',
    storageBucket: 'shikakugame-ddfcf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJgJ45AVUh4fUdRWHHvnt0sH2NL8LghPg',
    appId: '1:545047816852:android:af6cbf6362f88f7066e281',
    messagingSenderId: '545047816852',
    projectId: 'shikakugame-ddfcf',
    storageBucket: 'shikakugame-ddfcf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGLwTcSiFKs53auyjQJ4Ih5aUM2RKMLZs',
    appId: '1:545047816852:ios:3c0391d02b69484d66e281',
    messagingSenderId: '545047816852',
    projectId: 'shikakugame-ddfcf',
    storageBucket: 'shikakugame-ddfcf.appspot.com',
    iosClientId: '545047816852-omm6du209mtfdn9i0d7da9ev999qnubo.apps.googleusercontent.com',
    iosBundleId: 'com.example.minigames',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGLwTcSiFKs53auyjQJ4Ih5aUM2RKMLZs',
    appId: '1:545047816852:ios:3c0391d02b69484d66e281',
    messagingSenderId: '545047816852',
    projectId: 'shikakugame-ddfcf',
    storageBucket: 'shikakugame-ddfcf.appspot.com',
    iosClientId: '545047816852-omm6du209mtfdn9i0d7da9ev999qnubo.apps.googleusercontent.com',
    iosBundleId: 'com.example.minigames',
  );
}
